### ISSUE TITLE
Buffer is not defined

### ISSUE THREAD

**Issue by macterra** [Nintondo/browser-hdkey#1]
What's the work around?

```
ReferenceError: Buffer is not defined
    at hdkey.js:7:23
```

**Comment by macterra** [comment]
It works when I add the import to a local copy of the source:

```
import { Buffer } from 'buffer';
const MASTER_SECRET = Buffer.from("Bitcoin seed", "utf8");
```

**Comment by kieled** [comment]
Actually we use esbuild and this package is used in an extension that includes all the necessary configuration to prevent errors like those that occur in your environment. You can find this configuration here: https://github.com/Nintondo/extension/blob/main/build.ts
